### ISSUE TITLE
 Symbol "START" not found in the CERAMIC package. can you help me

### ISSUE THREAD

**Issue by leyap** [ceramic/ceramic#38]
- (ceramic:start)

debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
# <THREAD "main thread" RUNNING {10029ACA13}>:

  Symbol "START" not found in the CERAMIC package.

**Comment by eudoxia0** [comment]
Have you pulled the latest from GitHub? I've recently rewritten most of it.

**Comment by leyap** [comment]
after that I try the latest from GitHub for the whole night, but still can't work:

``` lisp
(ceramic:setup)
(ceramic:start)
```

I get error:
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lisper/.ceramic/electron/Electron.app/Contents/Resources/default_app/main.js:1:80)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Object.<anonymous> (/Users/lisper/.ceramic/electron/Electron.app/Contents/Resources/atom.asar/browser/lib/init.js:104:10)

then I try:

``` lisp
;;;app.lisp
(ql:quickload '(:ceramic :lucerne-utweet))
(ceramic:setup)
(ceramic:interactive)
```

I get error:
Symbol "INTERACTIVE" not found in the CERAMIC package.

**Comment by eudoxia0** [comment]
That's weird. I think you might be using older versions of some new dependencies. First, try deleting the entire cache (`~/.cache/common-lisp`). Then, clone these libraries to your Quicklisp `local-projects` directory:

```
https://github.com/ceramic/electron-tools
https://github.com/ceramic/copy-directory
https://github.com/ceramic/remote-js
https://github.com/ceramic/trivial-ws
https://github.com/ceramic/trivial-compress
https://github.com/eudoxia0/trivial-extract
```

Then, open a new Lisp image and load Ceramic.

Also, the new version of the API has dropped the `interactive` function. I updated the documentation, but not the code on the main project page.

**Comment by leyap** [comment]
Finally,  it works,  it is amazing. I use your suggest and use su, but if not use su
I get error:
[83050:0406/013806:ERROR:crash_report_database_mac.mm(86)] mkdir: No such file or directory
[0406/013806:ERROR:crash_report_database_mac.mm(86)] mkdir: No such file or directory
READY
